version: '3.*'

services:
  everest-test:
    build:
      context: .
      no_cache: true
    container_name: front-test
    env_file:
      - .env
      - .env.test
      - path: .env.local
        required: false
      - path: .env.test.local
        required: false
    restart: always
    ports:
      - ${PORT}:${PORT}
