export * from './methods/catalog'
export * from './methods/main-page'
export * from './methods/catalog-details'

export * from './methods/getAddresses'
export * from './methods/getLinks'
export * from './methods/getServices'
export * from './methods/getSocials'
export * from './methods/sendCallRequest'
export * from './methods/getFilters'
