name: Build and test

on:
  push:
    branches: ['master']
    paths:
      - '**/*'
      - '!**/*.md'
      - '!.idea'
  pull_request:
    branches: ['master']
    paths:
      - '**/*'
      - '!**/*.md'
      - '!.idea'
  workflow_dispatch:

jobs:
  build:
    name: 'build, type check and linting'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install pnpm via corepack
        run: corepack enable pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build Next.JS app
        run: pnpm run build

      - name: Upload build to artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: .next
          retention-days: 1

  unit-tests:
    name: 'unit and functional tests via vitest'
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install pnpm via corepack
        run: corepack enable pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run vitest tests
        run: pnpm run test

  e2e-tests:
    name: 'e2e tests via playwright'
    needs: build
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download build from artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: .next

      - name: Install Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install pnpm via corepack
        run: corepack enable pnpm

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Run Playwright tests
        run: pnpm exec playwright test

      - name: Upload report to artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7
