name: Run e2e tests via playwright

on:
  push:
    branches: ['master']
    paths:
      - '**/*'
      - '!**/*.md'
      - '!.idea'
  pull_request:
    branches: ['master']
    paths:
      - '**/*'
      - '!**/*.md'
      - '!.idea'
  workflow_dispatch:

jobs:
  e2e-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.45.1-jammy
    steps:
      - uses: actions/checkout@v4

      - name: Download build from artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: .next

      - name: Install Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install pnpm via corepack
        run: corepack enable pnpm

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Run Playwright tests
        run: pnpm exec playwright test

      - name: Upload report to artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7
