name: Production deploy

on:
  release:
    types: [released]

env:
  URL: https://everest.aaccent.su
  FOLDER: everest-front
  TARGET_PATH: /root/front-folders/${{ env.FOLDER }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: chrnorm/deployment-action@v2
        name: Create GitHub deployment
        id: production
        with:
          token: '${{ github.token }}'
          environment-url: ${{ env.URL }}

      - uses: actions/checkout@v4
        with:
          path: ${{ env.FOLDER }}
          ref: ${{ github.ref_name }}

      - uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "${{ env.FOLDER }}/*"
          target: ${{ env.TARGET_PATH }}
          strip_components: 1

      - name: Connect via ssh and run deploy script
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd ${{ env.TARGET_PATH }}
            docker compose up -d --build --force-recreate everest
            rm -r ${{ env.TARGET_PATH }}

      - name: Set success deployment
        if: success()
        uses: chrnorm/deployment-status@v2
        with:
          token: '${{ github.token }}'
          environment-url: ${{ env.URL }}
          state: 'success'
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}

      - name: Set failure deployment
        if: failure()
        uses: chrnorm/deployment-status@v2
        with:
          token: '${{ github.token }}'
          environment-url: ${{ env.URL }}
          state: 'failure'
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
