name: Unit and functional tests via vitest

on:
  push:
    branches: ['master']
    paths:
      - '**/*'
      - '!**/*.md'
      - '!.idea'
  pull_request:
    branches: ['master']
    paths:
      - '**/*'
      - '!**/*.md'
      - '!.idea'
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install pnpm via corepack
        run: corepack enable pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run vitest tests
        run: pnpm run test
